package org.eclipse.jgit.internal.storage.file.midx;

import static org.junit.Assert.assertNotNull;

import org.eclipse.jgit.junit.JGitTestUtil;
import org.junit.Test;

/**
 * Test MIDXLoader by reading the commit-graph file generated by Cgit.
 */
public class MIDXLoaderTest {

	private MIDX midx;

	@Test
	public void readMIDXV1() throws Exception {
		midx = MIDXLoader
				.open(JGitTestUtil.getTestResourceFile("multi-pack-index.v1"));
		assertNotNull(midx);
	}
}
