/*
 * Copyright (C) 2024, GerritForge Inc. and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0 which is available at
 * https://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package org.eclipse.jgit.internal.storage.file.midx;

import org.eclipse.jgit.junit.JGitTestUtil;
import org.eclipse.jgit.lib.ObjectId;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Test MultiPackIndexLoader by reading the multi-pack-index file generated by Cgit.
 */
public class MultiPackIndexLoaderTest {

    public static final int NUMBER_OF_PACKFILES = 26;
    private static final String[] PACKFILE_NAMES = {
            "pack-15d67b35f2b6a66ff995e09cedb36b101e0e0262.idx",
            "pack-1a979514a5965e71523187a17806e03af44344ed.idx",
            "pack-1de6731c035633ba8f5b41dacbc680a5a36ddd90.idx",
            "pack-1ee98948e4e362c56f3cdec7f5837d06e152854f.idx",
            "pack-1f6fe52ac3d33f3091d8eb8497474554bfa80bc4.idx",
            "pack-34b1aa6b437a9d968412454204c2676a88dc55fa.idx",
            "pack-3b245f7b4aff32a52d0520608f662bbf403792b9.idx",
            "pack-47901f7f8d1c440492035c4165796a330c7f79e0.idx",
            "pack-4e7f889b79aea8905a0062ce1bd68e5ef3af6a55.idx",
            "pack-71ea652e4aea2cbc609545b4fbc3eda6325d88a1.idx",
            "pack-723b1238411a4257c18167e91fbabed313ba332f.idx",
            "pack-7bd57092a7daa4dc31277e1ec86f3de8d968ae17.idx",
            "pack-883d4f469c5ea0f6d373ee623a758aeaf17715fc.idx",
            "pack-8eadd378a011ddaa5ec751f2a6d9789ef501120f.idx",
            "pack-92221b6f79a211944ccc6740fc22c9553ea1ba22.idx",
            "pack-b139d0cae5f54c70d057a8f4d2cf99f0ae0c326c.idx",
            "pack-b4f5c96d1fa6b1fac17a2a43710693c5514a9224.idx",
            "pack-bed4bc1521f965e55a5a8a58dffaaefc70ea4753.idx",
            "pack-cdc6baa7d90707a3c0dac4c188f797f0f79b97bb.idx",
            "pack-d6d58a58fa24b74c8c082f4f63c4d2ddfb824cc9.idx",
            "pack-daec59ae07f1091f3b81bd8266481bb5db3c868a.idx",
            "pack-e2197d60e09ad9091407eff4e06d39ec940851e1.idx",
            "pack-e4b191e4343f2b7ff851026c2d8595a001077344.idx",
            "pack-eedf783b5da4caa57be33b08990fe57f245a7413.idx",
            "pack-efb23e968801b9050bc70f0115a8a0eec88fb879.idx",
            "pack-f919c0660c207ddf6bb0569a3041d682d19fb4f7.idx"
    };
    private MultiPackIndex midx;

    @Test
    public void readMultiPackIndexV1() throws Exception {
        midx = MultiPackIndexLoader
                .open(JGitTestUtil.getTestResourceFile("multi-pack-index.v1"));
        assertNotNull(midx);

        assertEquals(NUMBER_OF_PACKFILES, midx.getPackFilesCount());
        assertEquals(NUMBER_OF_PACKFILES, midx.getPackFileNames().length);
        assertArrayEquals(PACKFILE_NAMES, midx.getPackFileNames());

        MultiPackIndex.ObjectOffset oo = midx.getObjectOffset(ObjectId.fromString("3f4ee50f784c1e9550f09a67d2ffc1bc76917bdc"));

        assertEquals(258, oo.getOffset());
        assertEquals(22, oo.getPackIntId());
        assertEquals("pack-e4b191e4343f2b7ff851026c2d8595a001077344.idx", midx.getPackFileName(oo.getPackIntId()));
    }
}
