jakarta.servlet=javax.servlet
jakarta.servlet.annotation=javax.servlet.annotation
jakarta.servlet.http=javax.servlet.http
org.eclipse.jetty.ee10.servlet=org.eclipse.jetty.ee8.servlet
org.eclipse.jetty.ee10.servlet.security=org.eclipse.jetty.ee8.security
