/*
 * Copyright (C) 2015, Google Inc.
 * and other copyright owners as documented in the project's IP log.
 *
 * This program and the accompanying materials are made available
 * under the terms of the Eclipse Distribution License v1.0 which
 * accompanies this distribution, is reproduced below, and is
 * available at http://www.eclipse.org/org/documents/edl-v10.php
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above
 *   copyright notice, this list of conditions and the following
 *   disclaimer in the documentation and/or other materials provided
 *   with the distribution.
 *
 * - Neither the name of the Eclipse Foundation, Inc. nor the
 *   names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior
 *   written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.eclipse.jgit.transport;

import static org.junit.Assert.assertEquals;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.jgit.internal.storage.dfs.DfsRepositoryDescription;
import org.eclipse.jgit.internal.storage.dfs.InMemoryRepository;
import org.eclipse.jgit.lib.CommitBuilder;
import org.eclipse.jgit.lib.Constants;
import org.eclipse.jgit.lib.PersonIdent;
import org.eclipse.jgit.lib.RefUpdate;
import org.junit.Before;
import org.junit.Test;

public class PushCertificateStoreTest {
	// Example push certificate generated by C git 2.2.0.
	private static final PushCertificate CERT1 = parseCertificate(
			"certificate version 0.1\n"
			+ "pusher Dave Borowitz <dborowitz@google.com> 1433954361 -0700\n"
			+ "pushee git://localhost/repo.git\n"
			+ "nonce 1433954361-bde756572d665bba81d8\n"
			+ "\n"
			+ "0000000000000000000000000000000000000000"
			+ " 6c2b981a177396fb47345b7df3e4d3f854c6bea7"
			+ " refs/heads/master\n"
			+ "-----BEGIN PGP SIGNATURE-----\n"
			+ "Version: GnuPG v1\n"
			+ "\n"
			+ "iQEcBAABAgAGBQJVeGg5AAoJEPfTicJkUdPkUggH/RKAeI9/i/LduuiqrL/SSdIa\n"
			+ "9tYaSqJKLbXz63M/AW4Sp+4u+dVCQvnAt/a35CVEnpZz6hN4Kn/tiswOWVJf4CO7\n"
			+ "htNubGs5ZMwvD6sLYqKAnrM3WxV/2TbbjzjZW6Jkidz3jz/WRT4SmjGYiEO7aA+V\n"
			+ "4ZdIS9f7sW5VsHHYlNThCA7vH8Uu48bUovFXyQlPTX0pToSgrWV3JnTxDNxfn3iG\n"
			+ "IL0zTY/qwVCdXgFownLcs6J050xrrBWIKqfcWr3u4D2aCLyR0v+S/KArr7ulZygY\n"
			+ "+SOklImn8TAZiNxhWtA6ens66IiammUkZYFv7SSzoPLFZT4dC84SmGPWgf94NoQ=\n"
			+ "=XFeC\n"
			+ "-----END PGP SIGNATURE-----\n");

	private static final PushCertificate CERT2 = parseCertificate(
			"certificate version 0.1\n"
			+ "pusher Dave Borowitz <dborowitz@google.com> 1435698874 -0700\n"
			+ "pushee git://localhost/repo.git\n"
			+ "nonce 1435698874-40a5a8eb8f01f2427521\n"
			+ "\n"
			+ "6c2b981a177396fb47345b7df3e4d3f854c6bea7"
			+ " b6ce11496ab36260941ecf4e905506baba91268b"
			+ " refs/heads/master\n"
			+ "-----BEGIN PGP SIGNATURE-----\n"
			+ "Version: GnuPG v1\n"
			+ "\n"
			+ "iQEcBAABAgAGBQJVkwa6AAoJEPfTicJkUdPklyIH/23yLNFlFxG67S00cEMXhc7t\n"
			+ "IQ8IbLknaPofDlI+qKE8SYhpNWx2M3AAsUW49YBwIg86QwsRbMvoE42TkheEPKoT\n"
			+ "iYu5OfyAuu7bLF3Qrl6zs6xftLPegRcBZ9djjBjh6U+qkgnp7puNgpw1UGfY87Fq\n"
			+ "gq/wD+IyD3Dni9E21fMEHntdTmOqZELvOBf2KXMDeSIQewUq6hOpzMt9/w0umucv\n"
			+ "SOA4S1+c4tZGswZVIGNLfyHbDDUxLYMoZbPo09wamNMVqjpdew23Xe/+pit1jhMs\n"
			+ "8AJ1iaPnU+X/cicCr6L/Z1eaXMeoK+TdyYRBHdVR5YY04bPYH2Wz2un/XhmYjmo=\n"
			+ "=YKLa\n"
			+ "-----END PGP SIGNATURE-----\n");

	private static PushCertificate parseCertificate(String str) {
		try {
			return PushCertificateParser.fromReader(new InputStreamReader(
					new ByteArrayInputStream(Constants.encode(str))));
		} catch (IOException e) {
			throw new IllegalArgumentException(e);
		}
	}

	private AtomicInteger ts = new AtomicInteger(1433954361);
	private InMemoryRepository repo;
	private PushCertificateStore store;

	@Before
	public void setUp() {
		repo = new InMemoryRepository(new DfsRepositoryDescription("repo"));
		store = newStore();
	}

	@Test
	public void missingRef() throws Exception {
		assertEquals(Collections.emptyList(), store.get("refs/heads/master"));
	}

	@Test
	public void saveOneCert() throws Exception {
		store.add("refs/heads/master", CERT1);
		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"));

		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));

		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"), CERT1);
		assertCertsEqual(store.get("refs/heads/branch"));
		assertCertsEqual(newStore().get("refs/heads/branch"));
	}

	@Test
	public void saveTwoCertsOnSameRefInSameUpdate() throws Exception {
		store.add("refs/heads/master", CERT1);
		store.add("refs/heads/master", CERT2);
		assertCertsEqual(store.get("refs/heads/master"), CERT1, CERT2);
		assertCertsEqual(newStore().get("refs/heads/master"));

		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));

		assertCertsEqual(store.get("refs/heads/master"), CERT1, CERT2);
		assertCertsEqual(newStore().get("refs/heads/master"), CERT1, CERT2);
		assertCertsEqual(store.get("refs/heads/branch"));
		assertCertsEqual(newStore().get("refs/heads/branch"));
	}

	@Test
	public void saveTwoCertsOnDifferentRefsInSameUpdate() throws Exception {
		store.add("refs/heads/master", CERT1);
		store.add("refs/heads/branch", CERT2);
		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"));
		assertCertsEqual(store.get("refs/heads/branch"), CERT2);
		assertCertsEqual(newStore().get("refs/heads/master"));

		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));

		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"), CERT1);
		assertCertsEqual(store.get("refs/heads/branch"), CERT2);
		assertCertsEqual(newStore().get("refs/heads/branch"), CERT2);
	}

	@Test
	public void saveTwoCertsOnSameRefInDifferentUpdate() throws Exception {
		store.add("refs/heads/master", CERT1);
		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"));

		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));

		store.add("refs/heads/master", CERT2);
		assertCertsEqual(store.get("refs/heads/master"), CERT1, CERT2);
		assertCertsEqual(newStore().get("refs/heads/master"), CERT1);

		assertEquals(RefUpdate.Result.FAST_FORWARD, store.save(newCommitBuilder()));

		assertCertsEqual(store.get("refs/heads/master"), CERT1, CERT2);
		assertCertsEqual(newStore().get("refs/heads/master"), CERT1, CERT2);
		assertCertsEqual(store.get("refs/heads/branch"));
		assertCertsEqual(newStore().get("refs/heads/branch"));
	}

	@Test
	public void saveTwoCertsOnDifferentRefsInDifferentUpdate() throws Exception {
		store.add("refs/heads/master", CERT1);
		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"));

		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));

		store.add("refs/heads/branch", CERT2);
		assertCertsEqual(store.get("refs/heads/branch"), CERT2);
		assertCertsEqual(newStore().get("refs/heads/branch"));

		assertEquals(RefUpdate.Result.FAST_FORWARD, store.save(newCommitBuilder()));

		assertCertsEqual(store.get("refs/heads/master"), CERT1);
		assertCertsEqual(newStore().get("refs/heads/master"), CERT1);
		assertCertsEqual(store.get("refs/heads/branch"), CERT2);
		assertCertsEqual(newStore().get("refs/heads/branch"), CERT2);
	}

	@Test
	public void saveCertWithLockFailure() throws Exception {
		store.add("refs/heads/master", CERT1);
		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));

		store.get("refs/heads/master"); // Cache old ref tip.
		store.add("refs/heads/master", CERT2);

		RefUpdate ru = repo.updateRef("refs/push-certs");
		ru.setForceUpdate(true);
		assertEquals(RefUpdate.Result.FORCED, ru.delete());

		assertEquals(RefUpdate.Result.LOCK_FAILURE, store.save(newCommitBuilder()));
		// Second save succeeds since ref was reread and delta reapplied.
		assertEquals(RefUpdate.Result.NEW, store.save(newCommitBuilder()));
		// First cert was lost when ref was deleted.
		assertCertsEqual(store.get("refs/heads/master"), CERT2);
	}

	private CommitBuilder newCommitBuilder() {
		PersonIdent ident = new PersonIdent(
				"A U. Thor", "author@example.com", ts.getAndIncrement(), 0);
		CommitBuilder cb = new CommitBuilder();
		cb.setAuthor(ident);
		cb.setCommitter(ident);
		cb.setMessage("Store push certificates");
		return cb;
	}

	private PushCertificateStore newStore() {
		return new PushCertificateStore(repo);
	}

	private static void assertCertsEqual(List<PushCertificate> actual,
			PushCertificate... expected) {
		assertEquals(expected.length, actual.size());
		for (int i = 0; i < expected.length; i++) {
			assertEquals("text of cert " + i,
					expected[i].toText(), actual.get(i).toText());
			assertEquals("signature of cert " + i,
					expected[i].getSignature(), actual.get(i).getSignature());
		}
	}
}
